# Generated by Django 5.1.2 on 2024-10-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE TABLE sample_mobile (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    model VARCHAR(50),
    brand VARCHAR(50)
);
            """,
            reverse_sql="""
DROP TABLE IF EXISTS sample_mobile;
            """
        ),
    ]
