# Generated by Django 5.1.2 on 2024-10-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE TABLE sample_techskills (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    type VARCHAR(50)
);
            """,
            reverse_sql="""
DROP TABLE IF EXISTS sample_techskills;
            """
        ),
    ]
