# Generated by Django 5.1.2 on 2024-10-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE TABLE sample_name (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    age VARCHAR(50)
);
            """,
            reverse_sql="""
DROP TABLE IF EXISTS sample_name;
            """
        ),
    ]
