# Generated by Django 5.1.2 on 2024-10-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_auto_20241028_0948'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE TABLE sample_favourites (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    type VARCHAR(50)
);
            """,
            reverse_sql="""
DROP TABLE IF EXISTS sample_favourites;
            """
        ),
    ]
