# Generated by Django 5.1.2 on 2024-10-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20241028_0959'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE TABLE sample_actors (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    role VARCHAR(50)
);
            """,
            reverse_sql="""
DROP TABLE IF EXISTS sample_actors;
            """
        ),
    ]
