# Generated by Django 5.1.2 on 2024-10-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_auto_20241028_1033'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE TABLE sample_mobile (
    id INT PRIMARY KEY,
    model VARCHAR(50),
    brand VARCHAR(50)
);
            """,
            reverse_sql="""
DROP TABLE IF EXISTS sample_mobile;
            """
        ),
    ]
